'use server';

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

/**
 * Input schema for pronunciation feedback requests.
 * Defines the word, the spoken audio as a base64 string, and the target language.
 */
const PronunciationFeedbackInputSchema = z.object({
  word: z.string().describe('The word to provide pronunciation feedback on.'),
  spokenWord: z.string().describe('The spoken word by the user as a base64 encoded audio data URL.'),
  language: z.enum(['en', 'de', 'fr', 'es', 'hi']).describe('The language of the word.'),
});
export type PronunciationFeedbackInput = z.infer<typeof PronunciationFeedbackInputSchema>;

/**
 * Output schema for pronunciation feedback responses.
 * Provides a score and qualitative feedback.
 */
const PronunciationFeedbackOutputSchema = z.object({
  feedback: z.string().describe('The pronunciation feedback.'),
  score: z.number().describe('Pronunciation accuracy score 0-1.'),
});
export type PronunciationFeedbackOutput = z.infer<typeof PronunciationFeedbackOutputSchema>;

/**
 * Gets pronunciation feedback for a spoken word.
 * @param input - The pronunciation feedback input containing word, audio, and language.
 * @returns Promise resolving to feedback and accuracy score.
 */
export async function getPronunciationFeedback(input: PronunciationFeedbackInput): Promise<PronunciationFeedbackOutput> {
  return pronunciationFeedbackFlow(input);
}

/**
 * AI flow that analyzes pronunciation and provides feedback.
 * Uses a multimodal model to process audio and provide structured feedback.
 */
const pronunciationFeedbackFlow = ai.defineFlow(
  {
    name: 'pronunciationFeedbackFlow',
    inputSchema: PronunciationFeedbackInputSchema,
    outputSchema: PronunciationFeedbackOutputSchema,
  },
  async (input) => {
    try {
      const { word, spokenWord, language } = input;

      const llmResponse = await ai.generate({
        model: 'googleai/gemini-1.5-flash',
        prompt: [
          {
            text: `You are a language teacher. Your task is to provide feedback on the user's pronunciation of a word.
          The user is trying to pronounce the word: "${word}" in ${language}.
          You will be given the user's spoken word as an audio file.
          Your task is to provide a short, encouraging, and constructive feedback on the user's pronunciation.
          Also, provide a pronunciation accuracy score from 0 to 1, where 1 is a perfect pronunciation.
          Your response should be in the language of the word.`
          },
          {
            media: {
              url: spokenWord,
              contentType: 'audio/webm',
            }
          }
        ],
        output: {
          schema: PronunciationFeedbackOutputSchema,
        },
      });

      const output = llmResponse.output;
      if (!output) {
        throw new Error('No feedback generated by the model.');
      }

      return output;
    } catch (error) {
      console.error('Pronunciation feedback error:', error);
      // Return a structured error response that matches the output schema
      return {
        feedback: error instanceof Error ? `Analysis failed: ${error.message}` : 'Unable to analyze pronunciation. Please try again.',
        score: 0
      };
    }
  }
);
