'use server';

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

/**
 * Input schema for pronunciation feedback requests.
 * Defines the word, the spoken audio as a base64 string, and the target language.
 */
/**
 * Schema for pronunciation feedback input.
 */
const PronunciationFeedbackInputSchema = z.object({
  /** The text of the word to analyze */
  word: z.string().describe('The word to provide pronunciation feedback on.'),
  /** Base64 encoded audio data (data URL format) */
  spokenWord: z.string().describe('The spoken word by the user as a base64 encoded audio data URL.'),
  /** The target language code (e.g., 'en', 'de') */
  language: z.enum(['en', 'de', 'fr', 'es', 'hi']).describe('The language of the word.'),
});
export type PronunciationFeedbackInput = z.infer<typeof PronunciationFeedbackInputSchema>;

/**
 * Output schema for pronunciation feedback responses.
 * Provides a score and qualitative feedback.
 */
const PronunciationFeedbackOutputSchema = z.object({
  feedback: z.string().describe('The pronunciation feedback.'),
  score: z.number().describe('Pronunciation accuracy score 0-1.'),
});
export type PronunciationFeedbackOutput = z.infer<typeof PronunciationFeedbackOutputSchema>;

/**
 * Gets pronunciation feedback for a spoken word.
 * @param input - The pronunciation feedback input containing word, audio, and language.
 * @returns Promise resolving to feedback and accuracy score.
 */
export async function getPronunciationFeedback(input: PronunciationFeedbackInput): Promise<PronunciationFeedbackOutput> {
  return pronunciationFeedbackFlow(input);
}

/**
 * AI flow that analyzes pronunciation and provides feedback.
 * Uses a multimodal model to process audio and provide structured feedback.
 */
const pronunciationFeedbackFlow = ai.defineFlow(
  {
    name: 'pronunciationFeedbackFlow',
    inputSchema: PronunciationFeedbackInputSchema,
    outputSchema: PronunciationFeedbackOutputSchema,
  },
  async (input) => {
    try {
      const { word, spokenWord, language } = input;

      // Validate input parameters
      if (!word?.trim()) {
        throw new Error('Word parameter is required and cannot be empty');
      }
      if (!spokenWord?.startsWith('data:audio/')) {
        throw new Error('Invalid audio data format');
      }
      if (!['en', 'de', 'fr', 'es', 'hi'].includes(language)) {
        throw new Error('Unsupported language');
      }

      const llmResponse = await ai.generate({
        model: 'googleai/gemini-1.5-flash',
        prompt: [
          {
            text: `You are a language teacher. Your task is to provide feedback on the user's pronunciation of a word.
          The user is trying to pronounce the word: "${word}" in ${language}.
          You will be given the user's spoken word as an audio file.
          Your task is to provide a short, encouraging, and constructive feedback on the user's pronunciation.
          Also, provide a pronunciation accuracy score from 0 to 1, where 1 is a perfect pronunciation.
          Your response should be in the language of the word.`
          },
          {
            media: {
              url: spokenWord,
              contentType: 'audio/webm',
            }
          }
        ],
        output: {
          schema: PronunciationFeedbackOutputSchema,
        },
      });

      const output = llmResponse.output;
      if (!output) {
        throw new Error('No feedback generated by the model');
      }

      // Validate output structure
      if (typeof output.feedback !== 'string' || typeof output.score !== 'number') {
        throw new Error('Invalid response format from AI model');
      }

      // Ensure score is within valid range
      const normalizedScore = Math.max(0, Math.min(1, output.score));

      return {
        feedback: output.feedback,
        score: normalizedScore
      };
    } catch (error) {
      console.error('Pronunciation feedback error:', error);

      // Categorize errors for better user experience
      let errorMessage = 'Unable to analyze pronunciation. Please try again.';

      if (error instanceof Error) {
        if (error.message.includes('audio') || error.message.includes('format')) {
          errorMessage = 'Audio format not supported. Please try recording again.';
        } else if (error.message.includes('model') || error.message.includes('generate')) {
          errorMessage = 'AI service temporarily unavailable. Please try again later.';
        } else if (error.message.includes('network') || error.message.includes('timeout')) {
          errorMessage = 'Network error. Please check your connection and try again.';
        }
      }

      return {
        feedback: errorMessage,
        score: 0
      };
    }
  }
);
