import type { Language } from './data';

export interface Resource {
    id: string;
    title: Record<Language, string>;
    description: Record<Language, string>;
    url: string;
    type: 'ebook' | 'video' | 'worksheet' | 'tool';
    languages: Language[];
    tags: string[];
}

export const resources: Resource[] = [
    // Ebooks
    {
        id: 'wikibooks-german-kids',
        title: {
            en: 'Wikibooks - German for Children',
            de: 'Wikibooks - Deutsch für Kinder',
            fr: 'Wikibooks - L\'allemand pour les enfants',
            es: 'Wikibooks - Alemán para niños',
            hi: 'विकिबुक्स - बच्चों के लिए जर्मन',
        },
        description: {
            en: 'A free open-content textbook for children to learn German, featuring basic vocabulary and simple grammar.',
            de: 'Ein freies Lehrbuch für Kinder zum Deutschlernen mit Grundwortschatz und einfacher Grammatik.',
            fr: 'Un manuel libre pour que les enfants apprennent l\'allemand, avec un vocabulaire de base et une grammaire simple.',
            es: 'Un libro de texto de contenido abierto gratuito para que los niños aprendan alemán, con vocabulario básico y gramática sencilla.',
            hi: 'बच्चों के लिए जर्मन सीखने के लिए एक मुफ़्त ओपन-कंटेंट पाठ्यपुस्तक, जिसमें बुनियादी शब्दावली और सरल व्याकरण शामिल है।',
        },
        url: 'https://en.wikibooks.org/wiki/German/German_for_Children',
        type: 'ebook',
        languages: ['en', 'de'],
        tags: ['wikibooks', 'german', 'beginner'],
    },
    {
        id: 'wikibooks-spanish-elementary',
        title: {
            en: 'Wikibooks - Elementary Spanish',
            de: 'Wikibooks - Spanisch für die Grundschule',
            fr: 'Wikibooks - Espagnol élémentaire',
            es: 'Wikibooks - Español elemental',
            hi: 'विकिबुक्स - प्रारंभिक स्पेनिश',
        },
        description: {
            en: 'An introductory Spanish textbook focused on conversational skills and basic concepts for young learners.',
            de: 'Ein einführendes Spanisch-Lehrbuch, das sich auf Konversationsfähigkeiten und Grundkonzepte für junge Lernende konzentriert.',
            fr: 'Un manuel d\'espagnol d\'introduction axé sur les compétences conversationnelles et les concepts de base pour les jeunes apprenants.',
            es: 'Un libro de texto de introducción al español enfocado en habilidades conversacionales y conceptos básicos para jóvenes estudiantes.',
            hi: 'युवा शिक्षार्थियों के लिए संवादात्मक कौशल और बुनियादी अवधारणाओं पर केंद्रित एक परिचयात्मक स्पेनिश पाठ्यपुस्तक।',
        },
        url: 'https://en.wikibooks.org/wiki/Elementary_Spanish',
        type: 'ebook',
        languages: ['en', 'es'],
        tags: ['wikibooks', 'spanish', 'beginner'],
    },
    {
        id: 'wikijunior-languages',
        title: {
            en: 'Wikijunior - Languages',
            de: 'Wikijunior - Sprachen',
            fr: 'Wikijunior - Langues',
            es: 'Wikijunior - Idiomas',
            hi: 'विकिजूनियर - भाषाएं',
        },
        description: {
            en: 'A colorful introduction to the languages of the world, designed specifically for children aged 8 to 12.',
            de: 'Eine farbenfrohe Einführung in die Sprachen der Welt, speziell für Kinder im Alter von 8 bis 12 Jahren entwickelt.',
            fr: 'Une introduction colorée aux langues du monde, conçue spécifiquement pour les enfants de 8 à 12 ans.',
            es: 'Una colorida introducción a los idiomas del mundo, diseñada específicamente para niños de 8 a 12 años.',
            hi: 'दुनिया की भाषाओं का एक रंगीन परिचय, विशेष रूप से 8 से 12 वर्ष की आयु के बच्चों के लिए डिज़ाइन किया गया।',
        },
        url: 'https://en.wikibooks.org/wiki/Wikijunior:Languages',
        type: 'ebook',
        languages: ['en', 'de', 'fr', 'es'],
        tags: ['wikijunior', 'multilingual', 'culture'],
    },
    {
        id: 'oer-global-storybooks',
        title: {
            en: 'Global Storybooks - Multilingual Tales',
            de: 'Global Storybooks - Mehrsprachige Erzählungen',
            fr: 'Global Storybooks - Contes multilingues',
            es: 'Global Storybooks - Cuentos multilingües',
            hi: 'ग्लोबल स्टोरीबुक्स - बहुभाषी कहानियाँ',
        },
        description: {
            en: 'Free, openly licensed storybooks for children in many different languages from OER Commons.',
            de: 'Kostenlose, offen lizenzierte Bilderbücher für Kinder in vielen verschiedenen Sprachen von OER Commons.',
            fr: 'Livres d\'histoires gratuits et sous licence libre pour enfants dans de nombreuses langues différentes d\'OER Commons.',
            es: 'Libros de cuentos gratuitos y con licencia abierta para niños en muchos idiomas diferentes de OER Commons.',
            hi: 'OER कॉमन्स से कई अलग-अलग भाषाओं में बच्चों के लिए मुफ्त, खुले तौर पर लाइसेंस प्राप्त कहानी की किताबें।',
        },
        url: 'https://globalstorybooks.net/',
        type: 'ebook',
        languages: ['en', 'de', 'fr', 'es', 'hi'],
        tags: ['stories', 'oer', 'reading'],
    },
    {
        id: 'coerll-grimm',
        title: {
            en: 'COERLL - Grimm Grammar (German)',
            de: 'COERLL - Grimm Grammatik (Deutsch)',
            fr: 'COERLL - Grimm Grammaire (Allemand)',
            es: 'COERLL - Gramática de Grimm (Alemán)',
            hi: 'COERLL - ग्रिम व्याकरण (जर्मन)',
        },
        description: {
            en: 'Explore German grammar through the enchanting lens of the Brothers Grimm fairy tales.',
            de: 'Entdecke die deutsche Grammatik durch die zauberhafte Brille der Märchen der Brüder Grimm.',
            fr: 'Explorez la grammaire allemande à travers le prisme enchanteur des contes de fées des frères Grimm.',
            es: 'Explora la gramática alemana a través de la lente encantadora de los cuentos de hadas de los hermanos Grimm.',
            hi: 'ब्रदर्स ग्रिम परियों की कहानियों के आकर्षक लेंस के माध्यम से जर्मन व्याकरण का अन्वेषण करें।',
        },
        url: 'https://www.coerll.utexas.edu/gg/',
        type: 'tool',
        languages: ['de'],
        tags: ['german', 'grammar', 'stories'],
    },
    {
        id: 'merlot-bbc-french',
        title: {
            en: 'MERLOT - BBC Schools French',
            de: 'MERLOT - BBC Schools Französisch',
            fr: 'MERLOT - BBC Schools Français',
            es: 'MERLOT - BBC Schools Francés',
            hi: 'MERLOT - बीबीसी स्कूल फ्रेंच',
        },
        description: {
            en: 'Interactive French games and activities for primary school students, indexed by MERLOT.',
            de: 'Interaktive französische Spiele und Aktivitäten für Grundschüler, indexiert von MERLOT.',
            fr: 'Jeux et activités interactives en français pour les élèves du primaire, indexés par MERLOT.',
            es: 'Juegos y actividades interactivas en francés para estudiantes de primaria, indexados por MERLOT.',
            hi: 'प्राथमिक विद्यालय के छात्रों के लिए इंटरैक्टिव फ्रेंच गेम और गतिविधियाँ, MERLOT द्वारा अनुक्रमित।',
        },
        url: 'https://www.merlot.org/merlot/viewMaterial.htm?id=83538',
        type: 'tool',
        languages: ['fr'],
        tags: ['french', 'games', 'primary'],
    },
    {
        id: 'coerll-spanish-tx',
        title: {
            en: 'COERLL - Spanish in Texas',
            de: 'COERLL - Spanisch in Texas',
            fr: 'COERLL - L\'espagnol au Texas',
            es: 'COERLL - El español en Texas',
            hi: 'COERLL - टेक्सास में स्पेनिश',
        },
        description: {
            en: 'Authentic Spanish language videos and activities focusing on real-world usage from COERLL.',
            de: 'Authentische spanische Sprachvideos und Aktivitäten mit Fokus auf den realen Gebrauch von COERLL.',
            fr: 'Vidéos et activités authentiques en langue espagnole axées sur l\'utilisation réelle de COERLL.',
            es: 'Videos y actividades auténticas en español enfocadas en el uso en el mundo real de COERLL.',
            hi: 'COERLL से वास्तविक दुनिया के उपयोग पर केंद्रित प्रामाणिक स्पेनिश भाषा के वीडियो और गतिविधियाँ।',
        },
        url: 'https://www.coerll.utexas.edu/spantex/',
        type: 'video',
        languages: ['es'],
        tags: ['spanish', 'video', 'culture'],
    },
    {
        id: 'oer-ck12-elementary',
        title: {
            en: 'CK-12 - Elementary Language Arts',
            de: 'CK-12 - Elementare Sprachkunst',
            fr: 'CK-12 - Arts du langage élémentaires',
            es: 'CK-12 - Artes del lenguaje elemental',
            hi: 'CK-12 - प्रारंभिक भाषा कला',
        },
        description: {
            en: 'Interactive FlexBooks and resources for English learning at an elementary level from OER Commons.',
            de: 'Interaktive FlexBooks und Ressourcen für das Englischlernen auf Grundschulniveau von OER Commons.',
            fr: 'FlexBooks et ressources interactives pour l\'apprentissage de l\'anglais au niveau élémentaire d\'OER Commons.',
            es: 'FlexBooks y recursos interactivos para el aprendizaje de inglés a nivel de primaria de OER Commons.',
            hi: 'OER कॉमन्स से प्राथमिक स्तर पर अंग्रेजी सीखने के लिए इंटरैक्टिव फ्लेक्सबुक्स और संसाधन।',
        },
        url: 'https://www.oercommons.org/hubs/ck12',
        type: 'tool',
        languages: ['en'],
        tags: ['english', 'interactive', 'textbooks'],
    },
    {
        id: 'merlot-german-quizzes',
        title: {
            en: 'MERLOT - German Vocabulary Quizzes',
            de: 'MERLOT - Deutsche Vokabelquizze',
            fr: 'MERLOT - Quiz de vocabulaire allemand',
            es: 'MERLOT - Quizzes de vocabulario alemán',
            hi: 'MERLOT - जर्मन शब्दावली प्रश्नोत्तरी',
        },
        description: {
            en: 'Self-correcting German vocabulary quizzes for beginners, curated via the MERLOT repository.',
            de: 'Selbstkorrigierende deutsche Vokabelquizze für Anfänger, kuratiert über das MERLOT-Repository.',
            fr: 'Quiz de vocabulaire allemand autocorrectifs pour débutants, organisés via le référentiel MERLOT.',
            es: 'Quizzes de vocabulario alemán autocorregibles para principiantes, seleccionados a través del repositorio MERLOT.',
            hi: 'शुरुआत करने वालों के लिए स्व-सुधार जर्मन शब्दावली प्रश्नोत्तरी, MERLOT रिपॉजिटरी के माध्यम से क्यूरेट की गई।',
        },
        url: 'https://www.merlot.org/merlot/viewMaterial.htm?id=77864',
        type: 'tool',
        languages: ['de'],
        tags: ['german', 'vocabulary', 'quiz'],
    },
    {
        id: 'storyberries',
        title: {
            en: 'Storyberries - Free Fairy Tales & Bedtime Stories',
            de: 'Storyberries - Kostenlose Märchen & Schlafenszeit-Geschichten',
            fr: 'Storyberries - Contes de fées et histoires pour dormir gratuits',
            es: 'Storyberries - Cuentos de hadas e historias para dormir gratis',
            hi: 'स्टोरीबेरीज़ - मुफ़्त परियों की कहानियाँ और सोने के समय की कहानियाँ',
        },
        description: {
            en: 'A huge collection of free online children\'s books, bedtime stories, and fairy tales in many languages.',
            de: 'Eine riesige Sammlung kostenloser Online-Kinderbücher, Gute-Nacht-Geschichten und Märchen in vielen Sprachen.',
            fr: 'Une vaste collection de livres pour enfants en ligne, d\'histoires pour dormir et de contes de fées gratuits dans de nombreuses langues.',
            es: 'Una enorme colección de libros infantiles en línea, historias para dormir y cuentos de hadas gratuitos en muchos idiomas.',
            hi: 'कई भाषाओं में मुफ़्त ऑनलाइन बच्चों की किताबों, सोने के समय की कहानियों और परियों की कहानियों का एक विशाल संग्रह।',
        },
        url: 'https://www.storyberries.com/',
        type: 'ebook',
        languages: ['en', 'de', 'fr', 'es', 'hi'],
        tags: ['stories', 'reading', 'multilingual'],
    },
    {
        id: 'fable-cottage',
        title: {
            en: 'The Fable Cottage - Bilingual Stories',
            de: 'The Fable Cottage - Zweisprachige Geschichten',
            fr: 'The Fable Cottage - Histoires bilingues',
            es: 'The Fable Cottage - Historias bilingües',
            hi: 'द फेबल कॉटेज - द्विभाषी कहानियाँ',
        },
        description: {
            en: 'Classic children\'s stories translated into multiple languages with parallel text and slow audio.',
            de: 'Klassische Kindergeschichten, übersetzt in mehrere Sprachen mit Paralleltext und langsamem Audio.',
            fr: 'Histoires classiques pour enfants traduites en plusieurs langues avec texte parallèle et audio lent.',
            es: 'Historias clásicas para niños traducidas a varios idiomas con texto paralelo y audio lento.',
            hi: 'समानांतर पाठ और धीमी ऑडियो के साथ कई भाषाओं में अनुवादित क्लासिक बच्चों की कहानियाँ।',
        },
        url: 'https://www.thefablecottage.com/',
        type: 'ebook',
        languages: ['en', 'de', 'fr', 'es', 'hi'],
        tags: ['bilingual', 'audio', 'classics'],
    },
    {
        id: 'unite-for-literacy',
        title: {
            en: 'Unite for Literacy',
            de: 'Unite for Literacy',
            fr: 'Unite for Literacy',
            es: 'Unite for Literacy',
            hi: 'यूनाइट फॉर लिटरेसी',
        },
        description: {
            en: 'Over 100 original e-books in English and Spanish with audio narration in 43 languages.',
            de: 'Über 100 Original-E-Books in Englisch und Spanisch mit Audio-Erzählung in 43 Sprachen.',
            fr: 'Plus de 100 livres électroniques originaux en anglais et en espagnol avec narration audio en 43 langues.',
            es: 'Más de 100 libros electrónicos originales en inglés y español con narración de audio en 43 idiomas.',
            hi: '43 भाषाओं में ऑडियो वर्णन के साथ अंग्रेजी और स्पेनिश में 100 से अधिक मूल ई-पुस्तकें।',
        },
        url: 'https://www.uniteforliteracy.com/',
        type: 'ebook',
        languages: ['en', 'es'],
        tags: ['picture books', 'audio'],
    },
    // Video Channels
    {
        id: 'easy-german-kids',
        title: {
            en: 'Easy German - Learning for Kids',
            de: 'Easy German - Lernen für Kinder',
            fr: 'Easy German - Apprentissage pour enfants',
            es: 'Easy German - Aprendizaje para niños',
            hi: 'ईज़ी जर्मन - बच्चों के लिए सीखना',
        },
        description: {
            en: 'Authentic German language learning through fun street interviews and daily life videos.',
            de: 'Authentisches Deutschlernen durch lustige Straßeninterviews und Alltagsvideos.',
            fr: 'Apprentissage authentique de l\'allemand à travers des interviews de rue amusantes et des vidéos de la vie quotidienne.',
            es: 'Aprendizaje auténtico de la lengua alemana a través de divertidas entrevistas callejeras y vídeos de la vida diaria.',
            hi: 'मजेदार स्ट्रीट इंटरव्यू और दैनिक जीवन के वीडियो के माध्यम से प्रामाणिक जर्मन भाषा सीखना।',
        },
        url: 'https://www.youtube.com/c/EasyGerman',
        type: 'video',
        languages: ['de'],
        tags: ['youtube', 'conversational', 'culture'],
    },
    {
        id: 'super-simple-songs',
        title: {
            en: 'Super Simple Songs - English',
            de: 'Super Simple Songs - Englisch',
            fr: 'Super Simple Songs - Anglais',
            es: 'Super Simple Songs - Inglés',
            hi: 'सुपर सिंपल सॉन्ग्स - अंग्रेजी',
        },
        description: {
            en: 'High-quality animated nursery rhymes and children\'s songs designed for learning English.',
            de: 'Hochwertige animierte Kinderreime und Kinderlieder zum Englischlernen.',
            fr: 'Des comptines et des chansons pour enfants animées de haute qualité conçues pour l\'apprentissage de l\'anglais.',
            es: 'Canciones infantiles animadas de alta calidad diseñadas für das Erlernen von Englisch.',
            hi: 'अंग्रेजी सीखने के लिए डिज़ाइन किए गए उच्च गुणवत्ता वाले एनिमेटेड नर्सरी राइम्स और बच्चों के गाने।',
        },
        url: 'https://www.youtube.com/user/SuperSimpleSongs',
        type: 'video',
        languages: ['en'],
        tags: ['songs', 'nursery rhymes', 'youtube'],
    },
    {
        id: 'chu-chu-tv-hindi',
        title: {
            en: 'ChuChu TV Hindi Rhymes',
            de: 'ChuChu TV Hindi Reime',
            fr: 'ChuChu TV Comptines Hindi',
            es: 'ChuChu TV Rimas en Hindi',
            hi: 'चूचू टीवी हिंदी राइम्स',
        },
        description: {
            en: 'Popular nursery rhymes and educational videos for kids in Hindi.',
            de: 'Beliebte Kinderreime und Lehrvideos für Kinder auf Hindi.',
            fr: 'Comptines populaires et vidéos éducatives pour enfants en hindi.',
            es: 'Rimas infantiles populares y videos educativos para niños en hindi.',
            hi: 'हिंदी में बच्चों के लिए लोकप्रिय नर्सरी राइम्स और शैक्षिक वीडियो।',
        },
        url: 'https://www.youtube.com/@ChuChuTVHindi',
        type: 'video',
        languages: ['hi'],
        tags: ['songs', 'nursery rhymes', 'youtube', 'hindi'],
    },
    {
        id: 'petit-ours-brun',
        title: {
            en: 'Petit Ours Brun - French Stories',
            de: 'Petit Ours Brun - Französische Geschichten',
            fr: 'Petit Ours Brun - Histoires en français',
            es: 'Petit Ours Brun - Historias en francés',
            hi: 'पेटिट ऑर्स ब्रून - फ्रांसीसी कहानियाँ',
        },
        description: {
            en: 'Gentle animated stories about daily routines and family themes in French.',
            de: 'Sanfte animierte Geschichten über Alltagsroutinen und Familienthemen auf Französisch.',
            fr: 'De douces histoires animées sur les routines quotidiennes et les thèmes familiaux en français.',
            es: 'Tiernas historias animadas sobre rutinas diarias y temas familiares en francés.',
            hi: 'फ्रांसीसी में दैनिक दिनचर्या और पारिवारिक विषयों के बारे में सौम्य एनिमेटेड कहानियाँ।',
        },
        url: 'https://www.youtube.com/c/PetitOursBrun',
        type: 'video',
        languages: ['fr'],
        tags: ['stories', 'daily life', 'youtube'],
    },
    {
        id: 'toy-cantando-spanish',
        title: {
            en: 'Toy Cantando - Spanish Songs',
            de: 'Toy Cantando - Spanische Lieder',
            fr: 'Toy Cantando - Chansons espagnoles',
            es: 'Toy Cantando - Canciones en español',
            hi: 'टॉय कैंटान्डो - स्पेनिश गाने',
        },
        description: {
            en: 'Classic Spanish nursery rhymes, fairy tales, and educational music for kids.',
            de: 'Klassische spanische Kinderreime, Märchen und Lernmusik für Kinder.',
            fr: 'Comptines espagnoles classiques, contes de fées et musique éducative pour enfants.',
            es: 'Clásicos villancicos, cuentos de hadas y música educativa para niños en español.',
            hi: 'बच्चों के लिए क्लासिक स्पेनिश नर्सरी राइम्स, परियों की कहानियाँ और शैक्षिक संगीत।',
        },
        url: 'https://www.youtube.com/user/toycantando',
        type: 'video',
        languages: ['es'],
        tags: ['songs', 'stories', 'youtube'],
    },
    // Worksheets
    {
        id: 'studycat-printables',
        title: {
            en: 'Studycat - Free Language Printables',
            de: 'Studycat - Kostenlose Sprachausdrucke',
            fr: 'Studycat - Imprimables linguistiques gratuits',
            es: 'Studycat - Imprimibles de idiomas gratuitos',
            hi: 'स्टडीकैट - मुफ़्त भाषा प्रिंटबल्स',
        },
        description: {
            en: 'Free printable worksheets for English, Spanish, French, and German for kids.',
            de: 'Kostenlose druckbare Arbeitsblätter für Englisch, Spanisch, Französisch und Deutsch für Kinder.',
            fr: 'Fiches d\'exercices gratuites à imprimer en anglais, espagnol, français et allemand pour les enfants.',
            es: 'Fichas de trabajo gratuitas para imprimir en inglés, español, francés y alemán para niños.',
            hi: 'बच्चों के लिए अंग्रेजी, स्पेनिश, फ्रेंच और जर्मन के लिए मुफ़्त प्रिंट करने योग्य वर्कशीट्स।',
        },
        url: 'https://studycat.com/printables/',
        type: 'worksheet',
        languages: ['en', 'de', 'fr', 'es'],
        tags: ['printables', 'exercises', 'vocabulary'],
    },
    {
        id: 'education-com-spanish',
        title: {
            en: 'Education.com - Spanish Worksheets',
            de: 'Education.com - Spanische Arbeitsblätter',
            fr: 'Education.com - Fiches d\'espagnol',
            es: 'Education.com - Fichas de español',
            hi: 'Education.com - स्पेनिश वर्कशीट्स',
        },
        description: {
            en: 'A wide range of Spanish learning worksheets from coloring pages to grammar exercises.',
            de: 'Eine breite Palette von Spanisch-Lernarbeitsblättern von Malvorlagen bis hin zu Grammatikübungen.',
            fr: 'Une large gamme de fiches d\'apprentissage de l\'espagnol, des coloriages aux exercices de grammaire.',
            es: 'Una amplia gama de fichas de aprendizaje de español, desde páginas para colorear hasta ejercicios de gramática.',
            hi: 'कलरिंग पेज से लेकर व्याकरण अभ्यास तक स्पेनिश सीखने की वर्कशीट्स की एक विस्तृत श्रृंखला।',
        },
        url: 'https://www.education.com/worksheets/spanish/',
        type: 'worksheet',
        languages: ['es'],
        tags: ['grammar', 'coloring', 'printables'],
    },
    // Tools
    {
        id: 'duolingo-kids',
        title: {
            en: 'Duolingo ABC',
            de: 'Duolingo ABC',
            fr: 'Duolingo ABC',
            es: 'Duolingo ABC',
            hi: 'डुओलिंगो एबीसी',
        },
        description: {
            en: 'A free app that helps children learn to read through fun, interactive games.',
            de: 'Eine kostenlose App, die Kindern hilft, das Lesen durch lustige, interaktive Spiele zu lernen.',
            fr: 'Une application gratuite qui aide les enfants à apprendre à lire grâce à des jeux amusantes.',
            es: 'Una aplicación gratuita que ayuda a los niños a aprender a leer a través de divertidos juegos interactivos.',
            hi: 'एक मुफ़्त ऐप जो बच्चों को मज़ेदार, इंटरैक्टिव खेलों के माध्यम से पढ़ना सीखने में मदद करता है।',
        },
        url: 'https://www.duolingo.com/abc',
        type: 'tool',
        languages: ['en', 'es', 'fr'],
        tags: ['app', 'reading', 'gamified'],
    },
    {
        id: 'british-council-kids',
        title: {
            en: 'British Council - LearnEnglish Kids',
            de: 'British Council - LearnEnglish Kids',
            fr: 'British Council - LearnEnglish Kids',
            es: 'British Council - LearnEnglish Kids',
            hi: 'ब्रिटिश काउंसिल - लर्नइंग्लिश किड्स',
        },
        description: {
            en: 'Free online games, songs, stories, and activities for children learning English.',
            de: 'Kostenlose Online-Spiele, Lieder, Geschichten und Aktivitäten für Kinder, die Englisch lernen.',
            fr: 'Jeux, chansons, histoires et activités en ligne gratuits pour les enfants qui apprennent l\'anglais.',
            es: 'Juegos, canciones, historias y actividades en línea gratuitos para niños que aprenden inglés.',
            hi: 'अंग्रेजी सीखने वाले बच्चों के लिए मुफ़्त ऑनलाइन गेम, गाने, कहानियाँ और गतिविधियाँ।',
        },
        url: 'https://learnenglishkids.britishcouncil.org/',
        type: 'tool',
        languages: ['en'],
        tags: ['games', 'activities', 'educational'],
    },
    {
        id: 'duolingo-podcast',
        title: {
            en: 'Duolingo Spanish/French Podcasts',
            de: 'Duolingo Spanisch/Französisch Podcasts',
            fr: 'Podcasts Duolingo Espagnol/Français',
            es: 'Podcasts de Duolingo en Español/Francés',
            hi: 'डुओलिंगो स्पेनिश/फ्रांसीसी पॉडकास्ट',
        },
        description: {
            en: 'Fascinating true stories for intermediate learners, delivered in easy-to-understand Spanish and French.',
            de: 'Faszinierende wahre Geschichten für Fortgeschrittene, erzählt in leicht verständlichem Spanisch und Französisch.',
            fr: 'Des histoires vraies fascinantes pour les apprenants intermédiaires, livrées en espagnol et en français faciles à comprendre.',
            es: 'Fascinantes historias reales para estudiantes de nivel intermedio, presentadas en español y francés fáciles de entender.',
            hi: 'मध्यवर्ती शिक्षार्थियों के लिए आकर्षक सच्ची कहानियाँ, समझने में आसान स्पेनिश और फ्रांसीसी में दी गई हैं।',
        },
        url: 'https://podcast.duolingo.com/',
        type: 'video',
        languages: ['es', 'fr'],
        tags: ['podcast', 'listening', 'stories'],
    },
    {
        id: 'digital-dialects',
        title: {
            en: 'Digital Dialects - Language Games',
            de: 'Digital Dialects - Sprachspiele',
            fr: 'Digital Dialects - Jeux linguistiques',
            es: 'Digital Dialects - Juegos de idiomas',
            hi: 'डिजिटल डायलेक्ट्स - भाषा खेल',
        },
        description: {
            en: 'Free to use games for learning 80 languages, including English, German, French, and Spanish.',
            de: 'Kostenlose Spiele zum Erlernen von 80 Sprachen, darunter Englisch, Deutsch, Französisch und Spanisch.',
            fr: 'Jeux gratuits pour apprendre 80 langues, dont l\'anglais, l\'allemand, le français et l\'espagnol.',
            es: 'Juegos gratuitos para aprender 80 idiomas, incluidos inglés, alemán, francés y español.',
            hi: 'अंग्रेजी, जर्मन, फ्रेंच और स्पेनिश सहित 80 भाषाओं को सीखने के लिए उपयोग करने में मुफ़्त खेल।',
        },
        url: 'https://www.digitaldialects.com/',
        type: 'tool',
        languages: ['en', 'de', 'fr', 'es', 'hi'],
        tags: ['games', 'vocabulary', 'interactive'],
    },
    {
        id: 'dav-pilkey-fun',
        title: {
            en: 'Dav Pilkey Fun Stuff',
            de: 'Dav Pilkey Fun Stuff',
            fr: 'Dav Pilkey Fun Stuff',
            es: 'Dav Pilkey Fun Stuff',
            hi: 'डेव पिलकी फन स्टफ',
        },
        description: {
            en: 'A massive collection of How to Draw guides and printable activities for Dog Man and Captain Underpants.',
            de: 'Eine riesige Sammlung von Zeichenanleitungen und druckbaren Aktivitäten für Dog Man und Captain Underpants.',
            fr: 'Une collection massive de guides de dessin et d\'activités imprimables pour Dog Man et Captain Underpants.',
            es: 'Una enorme colección de guías de dibujo y actividades imprimibles para Dog Man y Captain Underpants.',
            hi: 'डॉग मैन और कैप्टन अंडरपैंट्स के लिए हाउ टू ड्रा गाइड और प्रिंट करने योग्य गतिविधियों का एक विशाल संग्रह।',
        },
        url: 'https://www.pilkey.com/fun-stuff',
        type: 'worksheet',
        languages: ['en'],
        tags: ['dog man', 'drawing', 'printables', 'featured'],
    },
];
